using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PartialKittens
{
    /// <summary>
    /// Pretend this code was auto-generated by a tool... say, a mapper to a cat information database
    /// </summary>
    public partial class Tiger
    {
        public void FinishLoading()
        {
            Index(LoadRelatedSpecies());

            // if we *need* to load related species, even if no indexing implemented
            //var relSpecies = LoadRelatedSpecies();
            //Index(relSpecies);
        }

        private IEnumerable<WildCat> LoadRelatedSpecies()
        {
            Console.WriteLine("Loading my tiger cousins...");
            // pretend this comes from the database
            return new List<WildCat> { new Lion(), new Jaguar(), new Leapord() };
        }

        partial void Index(IEnumerable<WildCat> loadedRelatives);
    }

    public partial class Prey
    {
        public void FillReferences()
        {
            LoadPredators();
        }

        partial void LoadPredators();
    }
}