using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PartialKittens
{
    /// <summary>
    /// Pretend this code was auto-generated by a tool... say, a mapper to a cat information database
    /// </summary>
    public partial class Tiger
    {
        public void FillReferences()
        {
            LoadRelatedSpecies();
        }

        partial void LoadRelatedSpecies();
    }

    public partial class Prey
    {
        public void FillReferences()
        {
            LoadPredators();
        }

        partial void LoadPredators();
    }
}